"use client";import {useEffect,useRef,useState} from "react";import Studio from "./studio";
function OtpInput({value,onChange,autoFocus=false}:{value:string;onChange:(v:string)=>void;autoFocus?:boolean}){const refs=useRef<(HTMLInputElement|null)[]>([]),digits=Array.from({length:6},(_,i)=>value[i]||"");function setDigit(i:number,v:string){const n=v.replace(/\D/g,"").slice(-1),next=[...digits];next[i]=n;onChange(next.join(""));if(n&&i<5)refs.current[i+1]?.focus()}function paste(e:React.ClipboardEvent){e.preventDefault();const n=e.clipboardData.getData("text").replace(/\D/g,"").slice(0,6);onChange(n);refs.current[Math.min(n.length,5)]?.focus()}return <div className="otpBoxes" onPaste={paste} role="group" aria-label="Six-digit verification code">{digits.map((d,i)=><input key={i} ref={el=>{refs.current[i]=el}} autoFocus={autoFocus&&i===0} inputMode="numeric" autoComplete={i===0?"one-time-code":"off"} maxLength={1} value={d} aria-label={`Digit ${i+1}`} onChange={e=>setDigit(i,e.target.value)} onFocus={e=>e.target.select()} onKeyDown={e=>{if(e.key==="Backspace"&&!digits[i]&&i>0)refs.current[i-1]?.focus();if(e.key==="ArrowLeft"&&i>0)refs.current[i-1]?.focus();if(e.key==="ArrowRight"&&i<5)refs.current[i+1]?.focus()}}/>)}</div>}
export default function AuthGate({signedIn,verified,email}:{signedIn:boolean;verified:boolean;email?:string}){const[step,setStep]=useState(signedIn?"loading":"login"),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[qr,setQr]=useState(""),[secret,setSecret]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[recovery,setRecovery]=useState<string[]>([]),[ready,setReady]=useState(verified);
useEffect(()=>{if(signedIn&&!verified){setError("");fetch("/api/2fa/status").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Account security is unavailable");setStep(d.enabled?"verify":"setup")}).catch(e=>{setError(e instanceof Error?e.message:"Account security is unavailable");setStep("setup")})}},[signedIn,verified]);
async function setup(){setError("");setStep("loading");try{const r=await fetch("/api/2fa/setup",{method:"POST"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Setup failed");setQr(d.qr);setSecret(d.secret);setStep("scan")}catch(e){setError(e instanceof Error?e.message:"Unable to set up authenticator");setStep("setup")}}
async function login(e:React.FormEvent){e.preventDefault();setError("");try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password})}),d=await r.json();if(!r.ok){setError(d.error);return}setStep("loading");const status=await fetch("/api/2fa/status"),s=await status.json();if(!status.ok)throw new Error(s.error||"Security setup failed");setStep(s.enabled?"verify":"setup")}catch(e){setError(e instanceof Error?e.message:"Unable to sign in");setStep("login")}}
async function check(){setError("");const wasSetup=step==="scan";const r=await fetch("/api/2fa/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})}),d=await r.json();if(!r.ok){setError(d.error);return}if(wasSetup){setRecovery(d.recovery);setStep("recovery")}else setReady(true)}
if(ready)return <Studio/>;
return <main className="authPage"><section className="authBrand"><div className="authLogo">S2S</div><small>SOMETHING TO SHOW</small><h1>Your ideas.<br/><em>Professionally protected.</em></h1><p>Create, teach and present with confidence. Your studio is protected with two independent security factors.</p><div className="authArt"><i/><i/><i/></div></section><section className="authPanel"><div className="authCard">
{step==="login"&&<><span className="secureIcon">⌁</span><small>WELCOME TO S2S STUDIO</small><h2>Sign in to your studio</h2><p>Enter your studio owner credentials to continue.</p><form className="loginForm" onSubmit={login}><label>Username<input autoFocus autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter username"/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password"/></label>{error&&<p className="authError">{error}</p>}<button className="authPrimary" disabled={!username||!password}>Sign in securely <b>→</b></button></form><div className="securityNote">◈ Protected by encrypted credentials and Google Authenticator</div></>}
{step==="loading"&&<div className="authLoading"><i>✦</i><b>Checking account security…</b></div>}
{step==="setup"&&<><span className="secureIcon">◈</span><small>ACCOUNT SECURITY</small><h2>Enable two-factor authentication</h2><p>Add Google Authenticator for an extra layer of protection on <b>{email}</b>.</p><ol><li><b>1</b><span>Install Google Authenticator<small>Available on iOS and Android</small></span></li><li><b>2</b><span>Scan your secure QR code<small>It links this studio to your device</small></span></li><li><b>3</b><span>Confirm the six-digit code<small>Codes refresh every 30 seconds</small></span></li></ol>{error&&<p className="authError" role="alert">{error}</p>}<button className="authPrimary" onClick={setup}>Set up authenticator <b>→</b></button></>}
{step==="scan"&&<><small>SCAN WITH GOOGLE AUTHENTICATOR</small><h2>Connect your authenticator</h2><div className="qrFrame"><img src={qr} alt="Google Authenticator enrollment QR code"/></div><p className="manual">Can’t scan? Enter this key manually:<code>{secret}</code></p><label>Verification code<OtpInput autoFocus value={code} onChange={setCode}/></label>{error&&<p className="authError">{error}</p>}<button className="authPrimary" disabled={code.length!==6} onClick={check}>Verify and enable 2FA <b>→</b></button></>}
{step==="recovery"&&<><span className="secureIcon success">✓</span><small>2FA IS ACTIVE</small><h2>Save your recovery codes</h2><p>Store these one-time codes somewhere safe. They will not be shown again.</p><div className="recovery">{recovery.map(x=><code key={x}>{x}</code>)}</div><button className="authPrimary" onClick={()=>setReady(true)}>I saved them — enter studio <b>→</b></button></>}
{step==="verify"&&<><span className="secureIcon">◈</span><small>TWO-FACTOR VERIFICATION</small><h2>Enter your authenticator code</h2><p>Open Google Authenticator and enter the current code for S2S Studio.</p><label>Six-digit code<OtpInput autoFocus value={code} onChange={setCode}/></label>{error&&<p className="authError">{error}</p>}<button className="authPrimary" disabled={code.length!==6} onClick={check}>Verify identity <b>→</b></button><button className="authLink" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.reload()}}>Use another account</button></>}
</div></section></main>}
