import {env} from "cloudflare:workers";import {cookies} from "next/headers";
type AuthEnv={AUTH_USERNAME?:string;AUTH_PASSWORD?:string;AUTH_SESSION_SECRET?:string};const enc=new TextEncoder();
function config(){const e=env as unknown as AuthEnv;if(!e.AUTH_USERNAME||!e.AUTH_PASSWORD||!e.AUTH_SESSION_SECRET)throw new Error("Password authentication is not configured");return e}
async function digest(v:string){return new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v)))}
async function equal(a:string,b:string){const[x,y]=await Promise.all([digest(a),digest(b)]);if(x.length!==y.length)return false;let n=0;for(let i=0;i<x.length;i++)n|=x[i]^y[i];return n===0}
async function sign(v:string){const k=await crypto.subtle.importKey("raw",enc.encode(config().AUTH_SESSION_SECRET!),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const s=new Uint8Array(await crypto.subtle.sign("HMAC",k,enc.encode(v)));return btoa(String.fromCharCode(...s)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
export async function validateCredentials(username:string,password:string){const c=config();return (await equal(username,c.AUTH_USERNAME!))&&(await equal(password,c.AUTH_PASSWORD!))}
export async function createSession(username:string){const payload=btoa(JSON.stringify({u:username,e:Date.now()+43200000})).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");return payload+"."+await sign(payload)}
export async function createSecondFactorSession(username:string){const payload=btoa(JSON.stringify({u:username,f:2,e:Date.now()+43200000})).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");return payload+"."+await sign("2fa."+payload)}
export async function isSecondFactorVerified(username:string){const token=(await cookies()).get("s2s_2fa")?.value;if(!token)return false;const[payload,sig]=token.split(".");if(!payload||!sig||!await equal(sig,await sign("2fa."+payload)))return false;try{const data=JSON.parse(atob(payload.replaceAll("-","+").replaceAll("_","/"))) as {u:string;f:number;e:number};return data.u===username&&data.f===2&&data.e>=Date.now()}catch{return false}}
export async function getPasswordUser(){const token=(await cookies()).get("s2s_session")?.value;if(!token)return null;const[payload,sig]=token.split(".");if(!payload||!sig||!await equal(sig,await sign(payload)))return null;try{const data=JSON.parse(atob(payload.replaceAll("-","+").replaceAll("_","/"))) as {u:string;e:number};if(data.e<Date.now())return null;return {userId:"owner:"+data.u,displayName:data.u,email:data.u+"@s2s.studio"}}catch{return null}}
