"use client";
import {useEffect,useState} from "react";
import {SlideView,type Slide} from "./studio";
type Deck={id:string;title:string;slides:Slide[];updatedAt:number};
export default function PresenterPortal({name}:{name:string}){const[decks,setDecks]=useState<Deck[]>([]),[loading,setLoading]=useState(true),[active,setActive]=useState<Deck|null>(null),[slide,setSlide]=useState(0),[error,setError]=useState("");
useEffect(()=>{fetch("/api/presenter/presentations",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load presentations");setDecks(d.decks||[])}).catch(e=>setError(e instanceof Error?e.message:"Unable to load presentations")).finally(()=>setLoading(false))},[]);
useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!active)return;if(e.key==="ArrowRight"||e.key===" ")setSlide(i=>Math.min(active.slides.length-1,i+1));if(e.key==="ArrowLeft")setSlide(i=>Math.max(0,i-1));if(e.key==="Escape")setActive(null)};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[active]);
if(active)return <main className="present presenterShow"><button className="presenterExit" onClick={()=>setActive(null)}>× Exit presentation</button><div className="presentSlide"><SlideView s={active.slides[slide]} presenting/></div><div className="controls"><button onClick={()=>setSlide(i=>Math.max(0,i-1))}>←</button><span>{slide+1} / {active.slides.length}</span><button onClick={()=>setSlide(i=>Math.min(active.slides.length-1,i+1))}>→</button></div></main>;
return <main className="presenterPortal"><header><div className="presenterBrand"><b>S2S</b><span><strong>Presenter</strong><small>Something to show</small></span></div><div><span>Signed in as <b>{name}</b></span><button onClick={async()=>{await fetch("/api/presenter/logout",{method:"POST"});location.reload()}}>Sign out</button></div></header><section className="presenterHero"><small>PRESENTATION DESK</small><h1>Ready when you are.</h1><p>Choose an assigned presentation and take it straight to the screen.</p></section>{loading?<div className="presenterEmpty">Loading assigned presentations…</div>:error?<div className="presenterEmpty error">{error}</div>:decks.length===0?<div className="presenterEmpty"><b>No presentations assigned yet</b><span>Ask the studio owner to enable “Ready for presenter” on a presentation.</span></div>:<section className="presenterDecks">{decks.map((deck,index)=><article key={deck.id}><button onClick={()=>{setActive(deck);setSlide(0)}}><div className={`presenterCover tone${index%4}`}><small>{deck.slides.length} SLIDES</small><h2>{deck.title}</h2><span>▶ Start presentation</span></div><footer><b>{deck.title}</b><small>Updated {new Date(deck.updatedAt).toLocaleDateString()}</small></footer></button></article>)}</section>}</main>}
