"use client";
import {useEffect,useMemo,useState} from "react";
type View="home"|"create"|"bridge"|"blueprint"|"edit"|"present";
type Slide={id:number,title:string,tag:string,body:string,layout:string,notes:string};
const starter:Slide[]=[
{id:1,title:"Convolutional\nNeural Networks",tag:"VISUAL INTELLIGENCE • 60 MIN",body:"How machines learn to see — from pixels to patterns.",layout:"cover",notes:"Open with a question: how does a computer know there is a cat in a photo?"},
{id:2,title:"Why not a regular network?",tag:"THE CORE PROBLEM",body:"A 224 × 224 color image contains 150,528 values. Fully connecting them ignores where each pixel lives.",layout:"number",notes:"Contrast spatial awareness with a flattened list of pixels."},
{id:3,title:"An image is a matrix",tag:"01 • IMAGES AS DATA",body:"Each cell stores intensity. Color images stack three matrices — red, green and blue.",layout:"matrix",notes:"Ask learners to identify what the brightest cells represent."},
{id:4,title:"A tiny window,\na useful pattern",tag:"02 • CONVOLUTION",body:"A kernel slides across the image, multiplying and summing local values to detect edges, textures and shapes.",layout:"process",notes:"Use the window analogy. Spend about 4 minutes here."},
{id:5,title:"One filter, one feature map",tag:"03 • FEATURE MAPS",body:"Different filters light up different evidence: edges, curves, textures, then higher-level forms.",layout:"cards",notes:"Emphasize that filters are learned, not hand-coded."},
{id:6,title:"Keep the signal.\nShrink the noise.",tag:"04 • POOLING",body:"Max pooling preserves the strongest local activation while reducing spatial size and computation.",layout:"comparison",notes:"Walk through one 2×2 pooling calculation."},
{id:7,title:"From pixels to prediction",tag:"05 • ARCHITECTURE",body:"Image → Convolution → ReLU → Pooling → Dense layer → Class probabilities",layout:"architecture",notes:"Trace one image from left to right."},
{id:8,title:"A CNN in 7 lines",tag:"06 • BUILD IT",body:"model = Sequential([\n  Conv2D(32, 3, activation='relu'),\n  MaxPooling2D(),\n  Flatten(),\n  Dense(10, activation='softmax')\n])",layout:"code",notes:"Explain what each layer contributes."},
{id:9,title:"Learning is an\nerror-correction loop",tag:"07 • TRAINING",body:"Predict → Measure loss → Backpropagate → Update filters → Repeat",layout:"cycle",notes:"Connect the loop to familiar feedback systems."},
{id:10,title:"See locally.\nLearn hierarchically.",tag:"SUMMARY",body:"CNNs preserve spatial structure, learn reusable filters, and build complex ideas from simple visual features.",layout:"summary",notes:"Close with: why is convolution a better fit for images?"}];
const modes=["Teaching","Coding","Marketing","Business","Professional","Workshop","Research"];
function Logo(){return <div className="logo"><b>S2S</b><span>Studio</span></div>}
export default function Studio(){
 const[view,setView]=useState<View>("home"),[brief,setBrief]=useState("Teach CNN to engineering students in 60 minutes with practical Python examples"),[mode,setMode]=useState("Teaching"),[slides,setSlides]=useState(starter),[sel,setSel]=useState(0),[paste,setPaste]=useState(""),[error,setError]=useState(""),[tab,setTab]=useState("Copilot"),[toast,setToast]=useState("");const cur=slides[sel];
 const prompt=useMemo(()=>JSON.stringify({role:"Expert presentation architect and visual storyteller",task:"Create a concise, highly visual presentation blueprint. Return only valid JSON matching response_schema.",input:{brief,presentation_type:mode,audience:"Engineering students",duration_minutes:60,tone:"Clear and inspiring",visual_style:"Editorial modern"},rules:["8–12 slides","One core idea per slide","Prefer diagrams, code and examples","Include speaker notes"],response_schema:{title:"string",audience:"string",objectives:["string"],slides:[{title:"string",purpose:"string",layout:"string",key_message:"string",speaker_notes:"string"}]}},null,2),[brief,mode]);
 const flash=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)},update=(f:keyof Slide,v:string)=>setSlides(a=>a.map((s,i)=>i===sel?{...s,[f]:v}:s));
 function validate(){try{const d=JSON.parse(paste);if(!d.title||!Array.isArray(d.slides))throw 0;const a=d.slides.map((s:any,i:number)=>({id:i+1,title:s.title||`Slide ${i+1}`,tag:s.purpose||`SECTION ${i+1}`,body:s.key_message||"Add the key message",layout:s.layout||"content",notes:s.speaker_notes||""}));if(a.length)setSlides(a);setError("");flash("Valid JSON — blueprint ready");setTimeout(()=>setView("blueprint"),400)}catch{setError("That JSON isn’t ready yet. Check quotes, commas, title and slides.")}}
 useEffect(()=>{const k=(e:KeyboardEvent)=>{if(view!=="present")return;if(e.key==="ArrowRight"||e.key===" ")setSel(x=>Math.min(slides.length-1,x+1));if(e.key==="ArrowLeft")setSel(x=>Math.max(0,x-1));if(e.key==="Escape")setView("edit")};addEventListener("keydown",k);return()=>removeEventListener("keydown",k)},[view,slides.length]);
 if(view==="present")return <div className="present"><button className="exit" onClick={()=>setView("edit")}>× Exit</button><div className="presentSlide"><SlideView s={cur}/></div><div className="controls"><button disabled={!sel} onClick={()=>setSel(sel-1)}>←</button><span>{sel+1} / {slides.length}</span><button disabled={sel===slides.length-1} onClick={()=>setSel(sel+1)}>→</button><span>00:{String((sel+1)*3).padStart(2,"0")}</span></div></div>;
 return <main>{toast&&<div className="toast">✓ {toast}</div>}{view==="home"&&<Home create={()=>setView("create")} open={()=>setView("edit")}/>}
 {view==="create"&&<Create brief={brief} setBrief={setBrief} mode={mode} setMode={setMode} back={()=>setView("home")} next={()=>setView("bridge")}/>}
 {view==="bridge"&&<Bridge prompt={prompt} paste={paste} setPaste={setPaste} error={error} back={()=>setView("create")} copy={()=>{navigator.clipboard?.writeText(prompt);flash("Prompt copied — paste it into ChatGPT")}} demo={()=>setPaste(JSON.stringify({title:"Convolutional Neural Networks",slides:starter.map(s=>({title:s.title,purpose:s.tag,layout:s.layout,key_message:s.body,speaker_notes:s.notes}))},null,2))} validate={validate}/>}
 {view==="blueprint"&&<Blueprint slides={slides} setSlides={setSlides} back={()=>setView("bridge")} next={()=>setView("edit")}/>}
 {view==="edit"&&<Editor slides={slides} sel={sel} setSel={setSel} cur={cur} update={update} tab={tab} setTab={setTab} present={()=>setView("present")} add={()=>{setSlides([...slides,{id:slides.length+1,title:"Untitled idea",tag:"NEW SLIDE",body:"Start with one clear message.",layout:"content",notes:""}]);setSel(slides.length)}} flash={flash}/>}</main>}
function Side(){return <aside className="side"><Logo/><nav><button className="on">⌂ <span>Home</span></button><button>◇ <span>Templates</span></button><button>✦ <span>Brand kit</span></button><button>▧ <span>Assets</span></button></nav><footer><button>⚙ Settings</button><div className="user"><i>SR</i><span><b>Srikanth</b><small>Free workspace</small></span></div></footer></aside>}
function Home({create,open}:{create:()=>void;open:()=>void}){const cards=[["Convolutional Neural Networks","Teaching · 10 slides","CNNs","coral"],["React Hooks Workshop","Workshop · 18 slides","useEffect( )","navy"],["AI Product Launch","Marketing · 12 slides","Make it matter.","lime"],["Quarterly Business Review","Business · 24 slides","84% ↑","violet"]];return <><Side/><section className="home"><header><div className="search">⌕ <input placeholder="Search presentations, templates…"/><kbd>⌘ K</kbd></div><button>◐</button><button>♢</button><i>SR</i></header><div className="homeBody"><div className="welcome"><div><small>SATURDAY, 22 AUGUST</small><h1>Good evening, Srikanth.</h1><p>What do you want to show the world today?</p></div><button className="primary" onClick={create}>＋ Create presentation <em>⌘ N</em></button></div><Title over="PICK UP WHERE YOU LEFT OFF" title="Recent presentations"/><div className="cards">{cards.map((c,i)=><button key={c[0]} onClick={i?undefined:open}><div className={`cover ${c[3]}`}><small>STORY • {i+1}</small><b>{c[2]}</b><span>Something worth showing</span></div><div className="meta"><b>{c[0]}</b><span>•••</span><small>{c[1]}</small><small>Edited recently</small></div></button>)}</div><div className="homeGrid"><section><Title title="Start with a format"/><div className="formats">{modes.slice(0,6).map((x,i)=><button key={x} onClick={create}><i>{["◎","</>","↗","▦","⌁","✣"][i]}</i><b>{x}</b><span>→</span></button>)}</div></section><section className="ideas"><small>✦ AI IDEAS</small><h2>A little spark?</h2><p>Start with a thought. S2S will shape the story.</p>{["Turn course notes into a lecture","Create a hands-on coding workshop","Transform a report into a story"].map(x=><button onClick={create} key={x}>{x}<span>↗</span></button>)}</section></div></div></section></>}
function Title({over,title}:{over?:string,title:string}){return <div className="title">{over&&<small>{over}</small>}<h2>{title}</h2><button>View all →</button></div>}
function Top({back}:{back:()=>void}){return <header className="top"><Logo/><button onClick={back}>← Back</button></header>}
function Create({brief,setBrief,mode,setMode,back,next}:any){return <><Top back={back}/><div className="create"><small>01 / 03 · THE BRIEF</small><h1>What do you want<br/>to <em>show?</em></h1><p>Give us the raw idea. We’ll help shape the story.</p><div className="brief"><textarea value={brief} onChange={e=>setBrief(e.target.value)}/><footer><span>{brief.length} characters</span><button onClick={next}>Shape my story →</button></footer></div><label>Presentation type</label><div className="pills">{modes.map(x=><button className={mode===x?"on":""} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><div className="selects"><label>Audience<select><option>Engineering students</option></select></label><label>Duration<select><option>60 minutes</option></select></label><label>Tone<select><option>Clear & inspiring</option></select></label></div><div className="upload"><b>＋</b><span><strong>Add source material</strong><small>PDF, DOCX, PPTX, TXT or Markdown · optional</small></span><button>Browse</button></div></div></>}
function Bridge({prompt,paste,setPaste,error,back,copy,demo,validate}:any){return <><Top back={back}/><div className="bridge"><small>02 / 03 · AI HANDOFF</small><h1>Bring the intelligence.<br/><em>Keep the control.</em></h1><p>No API key needed. Copy our prompt to ChatGPT, then paste its answer back.</p><div className="handoff"><section><i>1</i><header><span><b>Copy the JSON prompt</b><small>Structured for reliable output</small></span><button onClick={copy}>⧉ Copy JSON</button></header><pre>{prompt}</pre><a href="https://chatgpt.com" target="_blank">Open ChatGPT ↗</a></section><strong>→</strong><section><i>2</i><header><span><b>Paste ChatGPT’s response</b><small>Validated before editing</small></span><button onClick={demo}>Use demo</button></header><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder={'Paste JSON here…\n\n{ "title": "…", "slides": […] }'}/>{error&&<p className="error">{error}</p>}<button className="primary" disabled={!paste} onClick={validate}>Validate & build blueprint →</button></section></div><footer>◈ Your content stays in your browser. Nothing is sent from S2S Studio.</footer></div></>}
function Blueprint({slides,setSlides,back,next}:any){return <><header className="blueTop"><Logo/><span>Blueprint</span><div><button onClick={back}>← Revise prompt</button><button className="primary" onClick={next}>Create presentation →</button></div></header><div className="blue"><aside><small>AI BLUEPRINT</small><h1>Convolutional<br/>Neural Networks</h1><dl><dt>Audience</dt><dd>Engineering students</dd><dt>Duration</dt><dd>60 minutes</dd><dt>Approach</dt><dd>Concept → visual intuition → code → practice</dd></dl><h3>Learning objectives</h3><ul><li>Explain why CNNs suit image data</li><li>Visualize convolution and pooling</li><li>Build a basic CNN in Python</li></ul><button>↻ Regenerate blueprint</button></aside><section><Title over="PRESENTATION FLOW" title={`${slides.length} slides · about 60 minutes`}/>{slides.map((s:Slide,i:number)=><div className="row" key={s.id}><i>⠿</i><b>{String(i+1).padStart(2,"0")}</b><span><input value={s.title.replace("\n"," ")} onChange={e=>setSlides(slides.map((x:Slide,j:number)=>j===i?{...x,title:e.target.value}:x))}/><small>{s.tag}</small></span><em>{s.layout}</em><button onClick={()=>setSlides(slides.filter((_:Slide,j:number)=>j!==i))}>×</button></div>)}<button className="add" onClick={()=>setSlides([...slides,{id:Date.now(),title:"New slide",tag:"NEW IDEA",body:"Add your key message",layout:"content",notes:""}])}>＋ Add a slide</button></section></div></>}
function Editor({slides,sel,setSel,cur,update,tab,setTab,present,add,flash}:any){return <div className="editor"><header><Logo/><div className="doc"><b>Convolutional Neural Networks</b><small>✓ Saved just now</small></div><nav>File　 Edit　 View　 ✦ AI</nav><div><button>↶</button><button>↷</button><button onClick={()=>flash("Review score: 89 · Strong audience fit")}>Review</button><button onClick={present}>▷ Present</button><button>Share</button><button className="darkBtn" onClick={()=>flash("Export ready: PDF, PPTX or PNG")}>Export⌄</button></div></header><div className="workspace"><aside className="slides"><div><b>Slides</b><span>{slides.length}</span></div><section>{slides.map((s:Slide,i:number)=><button className={i===sel?"on":""} onClick={()=>setSel(i)} key={s.id}><b>{i+1}</b><div className={`mini ${s.layout}`}><small>{s.tag}</small><strong>{s.title.replace("\n"," ")}</strong></div></button>)}</section><button onClick={add}>＋ Add slide</button></aside><section className="stage"><div className="toolbar">＋　 Inter⌄　 <b>B</b>　<i>I</i>　 ☷　 ◉　 ▦　　Layout⌄</div><div className="canvas"><div><SlideView s={cur} editable update={update}/></div></div><div className="notes"><header><b>Speaker notes</b><button onClick={()=>{update("notes",cur.notes||"Spend 3 minutes here. Explain with a familiar visual analogy, then ask learners to predict the next step.");flash("Speaker notes generated")}}>✦ Generate notes</button></header><textarea value={cur.notes} onChange={e=>update("notes",e.target.value)}/></div><footer><span>Slide {sel+1} of {slides.length}</span><span>−　━━━━　＋　72%</span></footer></section><aside className="copilot"><header>{["Copilot","Teaching","Design"].map(x=><button className={tab===x?"on":""} onClick={()=>setTab(x)} key={x}>{x==="Copilot"?"✦ ":""}{x}</button>)}</header>{tab==="Copilot"?<AI cur={cur} update={update} flash={flash}/>:tab==="Teaching"?<Teach cur={cur} update={update}/>:<Design flash={flash}/>}</aside></div></div>}
function SlideView({s,editable,update}:{s:Slide,editable?:boolean,update?:(f:keyof Slide,v:string)=>void}){const ed=editable?{contentEditable:true,suppressContentEditableWarning:true}:{};return <article className={`slide ${s.layout}`}><b className="brand">S2S<span>●</span></b><small>{s.tag}</small><h1 {...ed} onBlur={(e:any)=>update?.("title",e.currentTarget.innerText)}>{s.title}</h1><p {...ed} onBlur={(e:any)=>update?.("body",e.currentTarget.innerText)}>{s.body}</p>{s.layout==="number"&&<strong className="stat">150<span>K</span></strong>}{s.layout==="matrix"&&<div className="matrix">{[3,18,52,81,94,70,21,8,9,44,91,99,77,32,12,4].map((n,i)=><i key={i} style={{opacity:.2+n/125}}>{n}</i>)}</div>}{s.layout==="process"&&<div className="kernel"><i>3×3</i><span>→</span><b>FEATURE</b></div>}{s.layout==="architecture"&&<div className="arch">{["IMAGE","CONV","RELU","POOL","CLASS"].map((x,i)=><span key={x}>{x}{i<4&&<b>→</b>}</span>)}</div>}<em>{String(s.id).padStart(2,"0")}</em></article>}
function AI({cur,update,flash}:any){const simple=()=>{update("body",cur.body.split(/[.—]/)[0]+".");flash("Slide simplified")};return <div className="ai"><div className="context"><i>✦</i><span><b>Working on slide {cur.id}</b><small>{cur.title.replace("\n"," ")}</small></span></div><label>QUICK ACTIONS</label><div className="quick">{["Aa Simplify","⌘ More technical","＋ Add example","◇ Add diagram","≡ Reduce text","? Create quiz"].map(x=><button key={x} onClick={()=>x.includes("Simplify")||x.includes("Reduce")?simple():x.includes("diagram")?(update("layout","architecture"),flash("Diagram added")):flash(x.slice(2)+" ready")}>{x}</button>)}</div><div className="suggest"><small>✦ SUGGESTION</small><b>This slide could be more visual</b><p>Turn the concept into a step-by-step architecture diagram.</p><button onClick={()=>{update("layout","architecture");flash("Suggestion applied")}}>Apply</button> <button>Dismiss</button></div><div className="message">How can I make this easier for beginners?</div><div className="reply"><b>✦ S2S</b><p>Use one familiar analogy first, then reveal the technical term. Shorten the explanation to one sentence.</p><button onClick={simple}>Apply rewrite</button></div><div className="ask"><input placeholder="Ask about this slide…"/><button>↑</button></div></div>}
function Teach({cur,update}:any){return <div className="teach"><label>TEACHING LENS</label><h3>Learning objective</h3><textarea defaultValue="Explain the core idea in plain language and connect it to the full CNN workflow."/><div><span><small>Difficulty</small><b>Intermediate</b></span><span><small>Est. time</small><b>4 minutes</b></span></div><h3>Teacher notes</h3><textarea value={cur.notes} onChange={e=>update("notes",e.target.value)}/><h3>Discussion question</h3><p>What information might be lost if we make the kernel larger?</p><h3>Mini activity</h3><p>Give students a 5×5 matrix and apply one 3×3 filter.</p></div>}
function Design({flash}:any){return <div className="design"><label>THEME</label><h3>Choose a visual voice</h3><div>{[["Modern","#ef6b43"],["Technical","#7189e8"],["Academic","#ad8665"],["Dark","#222"],["Editorial","#c7dc62"],["Minimal","#ddd"]].map(x=><button key={x[0]} onClick={()=>flash(x[0]+" theme applied")}><i style={{background:x[1]}}></i><b>{x[0]}</b></button>)}</div></div>}
