import {env} from "cloudflare:workers";
import {getPasswordUser,isSecondFactorVerified} from "../../password-auth";
import {ensureStudioSchema} from "../../../db";
import {contentLengthTooLarge} from "../../api-security";

async function owner(){const user=await getPasswordUser();if(!user||!await isSecondFactorVerified(user.displayName))return null;return user}
type PresentationRow={id:string;title:string;slides_json:string;updated_at:number};
export async function GET(){const user=await owner();if(!user)return Response.json({error:"Unauthorized"},{status:401});await ensureStudioSchema();const result=await env.DB.prepare("SELECT id,title,slides_json,updated_at FROM presentations WHERE user_id=? ORDER BY updated_at DESC").bind(user.userId).all<PresentationRow>();return Response.json({decks:result.results.map(row=>({id:row.id,title:row.title,slides:JSON.parse(row.slides_json),updatedAt:row.updated_at}))})}
export async function POST(req:Request){const user=await owner();if(!user)return Response.json({error:"Unauthorized"},{status:401});if(contentLengthTooLarge(req,5_000_000))return Response.json({error:"Presentation is too large"},{status:413});let deck:{id?:string,title?:string,slides?:unknown[];updatedAt?:number};try{deck=await req.json()}catch{return Response.json({error:"Invalid presentation JSON"},{status:400})}if(!deck.id||deck.id.length>128||!deck.title||deck.title.length>240||!Array.isArray(deck.slides)||deck.slides.length>200)return Response.json({error:"Invalid presentation"},{status:400});const slidesJson=JSON.stringify(deck.slides);if(slidesJson.length>5_000_000)return Response.json({error:"Presentation is too large"},{status:413});await ensureStudioSchema();const updatedAt=typeof deck.updatedAt==="number"&&Number.isFinite(deck.updatedAt)&&deck.updatedAt>0?deck.updatedAt:Date.now();await env.DB.prepare("INSERT INTO presentations(id,user_id,title,slides_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,slides_json=excluded.slides_json,updated_at=excluded.updated_at WHERE user_id=excluded.user_id").bind(deck.id,user.userId,deck.title,slidesJson,updatedAt).run();return Response.json({ok:true,updatedAt})}
export async function DELETE(req:Request){const user=await owner();if(!user)return Response.json({error:"Unauthorized"},{status:401});if(contentLengthTooLarge(req,4_096))return Response.json({error:"Invalid request"},{status:413});const{id}=await req.json() as {id?:string};if(!id||id.length>128)return Response.json({error:"Presentation id is required"},{status:400});await ensureStudioSchema();await env.DB.prepare("DELETE FROM presentations WHERE id=? AND user_id=?").bind(id,user.userId).run();return Response.json({ok:true})}
